.TH "CustomTabButton" 3 "Wed Sep 6 2017" "Version 1.01" "AddWave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CustomTabButton \- Creates custom tab buttons for the tabbed components\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CustomLook\&.h>\fP
.PP
Inherits Component\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCustomTabButton\fP (bool &state)"
.br
.ti -1c
.RI "void \fBpaint\fP (Graphics &g) override"
.br
.ti -1c
.RI "void \fBmouseDown\fP (const MouseEvent &) override"
.br
.in -1c
.SH "Detailed Description"
.PP 
Creates custom tab buttons for the tabbed components\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CustomTabButton::CustomTabButton (bool & state)\fC [inline]\fP"

.PP
\fBParameters:\fP
.RS 4
\fIstate\fP Outputs which tab of the multislider is being affected 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for AddWave from the source code\&.
