.TH "CustomLook_V2" 3 "Wed Sep 6 2017" "Version 1.01" "AddWave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CustomLook_V2 \- Creates custom sliders\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CustomLook\&.h>\fP
.PP
Inherits LookAndFeel_V3\&.
.SH "Detailed Description"
.PP 
Creates custom sliders\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for AddWave from the source code\&.
