.TH "DelayControlView" 3 "Wed Sep 6 2017" "Version 1.01" "AddWave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DelayControlView \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Component\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDelayControlView\fP ()"
.br
.RI "\fICreates delay Controlc view\&. \fP"
.ti -1c
.RI "void \fBpaint\fP (Graphics &) override"
.br
.ti -1c
.RI "void \fBresized\fP () override"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ScopedPointer< Slider > \fBm_leftDelayTime\fP"
.br
.ti -1c
.RI "ScopedPointer< Slider > \fBm_rightDelayTime\fP"
.br
.ti -1c
.RI "ScopedPointer< Slider > \fBm_leftFeedback\fP"
.br
.ti -1c
.RI "ScopedPointer< Slider > \fBm_rightFeedback\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AddWave from the source code\&.
