.TH "Distortion" 3 "Wed Sep 6 2017" "Version 1.01" "AddWave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Distortion \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDistortion\fP (float thresh)"
.br
.ti -1c
.RI "float \fBdistort\fP (float sample, float thresh)    "
.br
.RI "\fIThis is how the distorion is implimented\&. \fP"
.ti -1c
.RI "void \fBset_distortion_amount\fP (float thresh)"
.br
.RI "\fISets the amount of the threshold\&. \fP"
.ti -1c
.RI "float \fBget_distortion_amount\fP (float thresh)"
.br
.RI "\fIReturns the amount of the threshold\&. \fP"
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "float Distortion::distort (float sample, float thresh)\fC [inline]\fP"

.PP
This is how the distorion is implimented\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsample\fP Sample to distort
.br
\fIthresh\fP Aggression of distortion 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for AddWave from the source code\&.
