.TH "EnvelopeController" 3 "Wed Sep 6 2017" "Version 1.01" "AddWave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EnvelopeController \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Listener, and Component\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEnvelopeController\fP (\fBSynthAudioProcessor\fP &envPlugin, \fBEnvelopeHPFilterView\fP &envHPFilterView, \fBEnvelopeLPFilterView\fP &envLPFilterView)"
.br
.ti -1c
.RI "void \fBsliderValueChanged\fP (Slider *slider)"
.br
.RI "\fICalled if slider is manipulated by mouse\&. \fP"
.ti -1c
.RI "void \fBupdateEnvSlider\fP ()"
.br
.RI "\fIUpdates UI components when UI reloaded\&. \fP"
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AddWave from the source code\&.
