.TH "EnvelopeLPFilterView" 3 "Wed Sep 6 2017" "Version 1.01" "AddWave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EnvelopeLPFilterView \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Component\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEnvelopeLPFilterView\fP ()"
.br
.RI "\fICreates the highpass filter design and layout\&. \fP"
.ti -1c
.RI "void \fBpaint\fP (Graphics &) override"
.br
.ti -1c
.RI "void \fBresized\fP () override"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ScopedPointer< Slider > \fBm_lpFilterAmountSlider\fP"
.br
.ti -1c
.RI "ScopedPointer< Slider > \fBm_lpFilterAttackSlider\fP"
.br
.ti -1c
.RI "ScopedPointer< Slider > \fBm_lpFilterDecaySlider\fP"
.br
.ti -1c
.RI "ScopedPointer< Slider > \fBm_lpFilterSustainSlider\fP"
.br
.ti -1c
.RI "ScopedPointer< Slider > \fBm_lpFilterReleaseSlider\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AddWave from the source code\&.
