.TH "Phasor" 3 "Wed Sep 6 2017" "Version 1.01" "AddWave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Phasor \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPhasor\fP (float SampleRate=44100, float Frequency=440)"
.br
.RI "\fIReads through the Wavetables\&. \fP"
.ti -1c
.RI "void \fBcalculate_inc\fP ()"
.br
.ti -1c
.RI "void \fBset_frequency\fP (float Frequency)"
.br
.RI "\fISets the frequency\&. \fP"
.ti -1c
.RI "void \fBset_samplerate\fP (float SampleRate)"
.br
.RI "\fISets the sample rate\&. \fP"
.ti -1c
.RI "float \fBget_phase\fP ()"
.br
.RI "\fIGets the current phase\&. \fP"
.ti -1c
.RI "void \fBreset\fP ()"
.br
.ti -1c
.RI "void \fBtick\fP ()"
.br
.RI "\fIreads through wave table \fP"
.ti -1c
.RI "float \fBget_frequency\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Phasor::Phasor (float SampleRate = \fC44100\fP, float Frequency = \fC440\fP)\fC [inline]\fP"

.PP
Reads through the Wavetables\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsampleRate\fP Sample Rate
.br
\fIFrequency\fP Frequency of signal 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for AddWave from the source code\&.
