.TH "PolySound" 3 "Wed Sep 6 2017" "Version 1.01" "AddWave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PolySound \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits SynthesiserSound\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBappliesToNote\fP (int) override"
.br
.ti -1c
.RI "bool \fBappliesToChannel\fP (int) override"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AddWave from the source code\&.
