.TH "ReverbControlView" 3 "Wed Sep 6 2017" "Version 1.01" "AddWave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ReverbControlView \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Component\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBReverbControlView\fP ()"
.br
.RI "\fICreates reverb Control view\&. \fP"
.ti -1c
.RI "void \fBpaint\fP (Graphics &) override"
.br
.ti -1c
.RI "void \fBresized\fP () override"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ScopedPointer< Slider > \fBm_reverbWet\fP"
.br
.ti -1c
.RI "ScopedPointer< Slider > \fBm_reverbDry\fP"
.br
.ti -1c
.RI "ScopedPointer< Slider > \fBm_reverbWidth\fP"
.br
.ti -1c
.RI "ScopedPointer< Slider > \fBm_reverbRoomSize\fP"
.br
.ti -1c
.RI "ScopedPointer< Slider > \fBm_reverbDamping\fP"
.br
.ti -1c
.RI "\fBCustomLook_V2\fP \fBm_whiteFeel\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AddWave from the source code\&.
